Hw03 submission - RBT tests left to be implemented and submitted
kajigor/fp-2023-cub-fall pull request #12
Opened 2023-10-16 21:41 UTC by razvanperial

2023-10-24 15:29 UTC, kajigor requested changes
There is a lot of code duplication everywhere, which should be got rid of.

2023-10-24 15:29 UTC, kajigor commented on test/Test/BankersDequeProp.hs
> +  x <- forAll $ Gen.int (Range.linear 0 100)
Create a dedicated generator of ints and use it instead of duplicating code

2023-10-24 15:29 UTC, kajigor commented on test/Test/BankersDequeProp.hs
> +  xs <- forAll $ Gen.list (Range.linear 0 100) (Gen.int (Range.linear 0 100))
Create list generator and use instead of duplicating code

2023-10-24 15:29 UTC, kajigor commented on test/Test/BankersDequeProp.hs
> +  , testProperty "prop_popFront" prop_popFront
Use descriptive names for tests

2023-10-24 15:29 UTC, kajigor commented on test/Test/BankersDequeProp.hs
> +-- test thet the popBack function removes the last element
It's better to describe the property in a comment with what exactly the property checks.

2023-10-24 15:29 UTC, kajigor commented on test/Test/QueueRealTimeProp.hs
> +
You have the same code in QueuePureFunctionalProp. Can you come up with a way to get rid of code duplication?

2023-11-01 18:27 UTC, razvanperial commented on test/Test/BankersDequeProp.hs
> +  x <- forAll $ Gen.int (Range.linear 0 100)
This should be resolved in the last commit

2023-11-01 18:28 UTC, razvanperial commented on test/Test/BankersDequeProp.hs
> +  xs <- forAll $ Gen.list (Range.linear 0 100) (Gen.int (Range.linear 0 100))
This should be resolved in the last commit

2023-11-01 18:28 UTC, razvanperial commented on test/Test/QueueRealTimeProp.hs
> +
I have tried to contralise the property based testing for Queues, so I believe this should be resolved in the last commit

2023-11-14 14:46 UTC, kajigor commented
ok

2023-11-14 14:46 UTC, closed without merging