hw03 submission (todo: property tests for rbtrees) - Tea Stefanovska
kajigor/fp-2023-cub-fall pull request #15
Opened 2023-10-17 15:51 UTC by tejchu

2023-10-24 15:22 UTC, kajigor requested changes
A lot of unnecessary code duplication which should be got rid of.

2023-10-24 15:22 UTC, kajigor commented on hw03/hw01/test/Test/BankersQueue.hs
> +    testProperty "prop_isEmpty" prop_isEmpty]
It's better to use the textual representation of the property as the description of the test.

2023-10-24 15:22 UTC, kajigor commented on hw03/hw01/test/Test/BankersQueue.hs
> +      else assert $ not $ isEmptyResult
This code is duplicated for each queue. Can you come up with a way to abstract it away to get rid of the duplication?

2023-10-26 10:17 UTC, tejchu commented on hw03/hw01/test/Test/BankersQueue.hs
> +    testProperty "prop_isEmpty" prop_isEmpty]
Is the current description okay, or should I make other changes?

2023-10-26 10:18 UTC, tejchu commented on hw03/hw01/test/Test/BankersQueue.hs
> +      else assert $ not $ isEmptyResult
I realized that, I have created a new file only for the property-based tests for the queues. Is this something that satisfies the request or should I do anything differently?

2023-11-14 14:44 UTC, kajigor commented
Ok

2023-11-14 14:44 UTC, closed without merging